### ISSUE TITLE
hi ,i have a question with compile

### ISSUE THREAD

**Issue by zyxia** [10110111/gdtoa#1]
int cmakefile.txt "${PROJECT_BINARY_DIR}/arith.h"
where is arith.h come from

**Comment by 10110111** [comment]
It comes from here:
https://github.com/10110111/gdtoa-desktop/blob/96aac69aa3288e6e835a990a32867ca0caa652e3/CMakeLists.txt#L167-L172
Does compilation fail for you?

**Comment by zyxia** [comment]
yes,it seems like that "arith.h" will generate automatic,and it is troublesome for me ,i just want to compile it.

**Comment by 10110111** [comment]
What exactly is your problem? Why is auto-generation troublesome? Are you trying to cross-compile?

**Comment by zyxia** [comment]
ok
